version: "3.3"

services:
    nextjs:
        container_name: musixverse-client
        ports:
            - 3000:3000
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./:/app
            - /app/node_modules
            - /app/.next
        env_file:
            - .env