export const TopArtistsData = [
	{
		name: "Sarthak Kalyani",
		instagramProfileURL: "https://www.instagram.com/sarthak.kalyani",
		imageURL_b: require("../../../../public/assets/new-homepage/sarthak_c_d.png"),
		imageURL_w: require("../../../../public/assets/new-homepage/sarthak_c_w.png"),
		description: "The singer who wowed AR Rahman",
		bgURL_d_b: require("../../../../public/assets/new-homepage/cover_sarthak_d.png"),
		bgURL_m_b: require("../../../../public/assets/new-homepage/sarthak_d.png"),
		bgURL_d_w: require("../../../../public/assets/new-homepage/cover_sarthak_w.png"),
		bgURL_m_w: require("../../../../public/assets/new-homepage/sarthak_w.png"),
	},
	{
		name: "Jatayu",
		instagramProfileURL: "https://www.instagram.com/jatayusounds",
		imageURL_b: require("../../../../public/assets/new-homepage/jatayu_c_d.png"),
		imageURL_w: require("../../../../public/assets/new-homepage/jatayu_c_w.png"),
		description: "A Jazz Rock Fusion Band introducing the world to Indian tunes",
		bgURL_d_b: require("../../../../public/assets/new-homepage/cover_jatayu_d.png"),
		bgURL_m_b: require("../../../../public/assets/new-homepage/jatayu_d.png"),
		bgURL_d_w: require("../../../../public/assets/new-homepage/cover_jatayu_w.png"),
		bgURL_m_w: require("../../../../public/assets/new-homepage/jatayu_w.png"),
	},
	{
		name: "Submarine in Space",
		instagramProfileURL: "https://www.instagram.com/submarine_in_space",
		imageURL_b: require("../../../../public/assets/new-homepage/submarine_c_d.png"),
		imageURL_w: require("../../../../public/assets/new-homepage/submarine_c_w.png"),
		description: "The Critically Acclaimed IInstrumental Jazz-Rock Band",
		bgURL_d_b: require("../../../../public/assets/new-homepage/cover_submarine_d.png"),
		bgURL_m_b: require("../../../../public/assets/new-homepage/submarine_d.png"),
		bgURL_d_w: require("../../../../public/assets/new-homepage/cover_submarine_w.png"),
		bgURL_m_w: require("../../../../public/assets/new-homepage/submarine_w.png"),
	},
	{
		name: "Sommaiya",
		instagramProfileURL: "https://www.instagram.com/sommaiya_angrish",
		imageURL_b: require("../../../../public/assets/new-homepage/sommaiya_c_d.png"),
		imageURL_w: require("../../../../public/assets/new-homepage/sommaiya_c_w.png"),
		description: "A Genreless Musician and Filmmaker leaving his mark from New Delhi to New York",
		bgURL_d_b: require("../../../../public/assets/new-homepage/cover_sommaiya_d.png"),
		bgURL_m_b: require("../../../../public/assets/new-homepage/sommaiya_d.png"),
		bgURL_d_w: require("../../../../public/assets/new-homepage/cover_sommaiya_w.png"),
		bgURL_m_w: require("../../../../public/assets/new-homepage/sommaiya_w.png"),
	},
	{
		name: "Harry Arora",
		instagramProfileURL: "https://www.instagram.com/harrythisside",
		imageURL_b: require("../../../../public/assets/new-homepage/harry_c_d.png"),
		imageURL_w: require("../../../../public/assets/new-homepage/harry_c_w.png"),
		description: "The singer touching all the right chords",
		bgURL_d_b: require("../../../../public/assets/new-homepage/cover_harry_d.png"),
		bgURL_m_b: require("../../../../public/assets/new-homepage/harry_d.png"),
		bgURL_d_w: require("../../../../public/assets/new-homepage/cover_harry_w.png"),
		bgURL_m_w: require("../../../../public/assets/new-homepage/harry_w.png"),
	},
	{
		name: "Xubaan",
		instagramProfileURL: "https://www.instagram.com/xubaanindia",
		imageURL_b: require("../../../../public/assets/new-homepage/xubaan_c_d.png"),
		imageURL_w: require("../../../../public/assets/new-homepage/xubaan_c_w.png"),
		description: "The band that is taking the world by storm",
		bgURL_d_b: require("../../../../public/assets/new-homepage/cover_xubaan_d.png"),
		bgURL_m_b: require("../../../../public/assets/new-homepage/xubaan_d.png"),
		bgURL_d_w: require("../../../../public/assets/new-homepage/cover_xubaan_w.png"),
		bgURL_m_w: require("../../../../public/assets/new-homepage/xubaan_w.png"),
	},
];
