export const TopArtistsData = [
	{
		name: "Sarthak Kalyani",
		instagramProfileURL: "https://www.instagram.com/sarthak.kalyani",
		imageURL: require("../../../../public/assets/new-homepage/sarthak_kalyani.png"),
		description: "The singer who wowed AR Rahman",
		bgURL_d: require("../../../../public/assets/new-homepage/cover_sarthak.png"),
		bgURL_m: require("../../../../public/assets/new-homepage/cover_m.png"),
	},
	{
		name: "Jatayu",
		instagramProfileURL: "https://www.instagram.com/jatayusounds",
		imageURL: require("../../../../public/assets/new-homepage/jatayu.png"),
		description: "A Jazz Rock Fusion Band introducing the world to Indian tunes",
		bgURL_d: require("../../../../public/assets/new-homepage/cover_jatayu.png"),
		bgURL_m: require("../../../../public/assets/new-homepage/cover_m.png"),
	},
	{
		name: "Submarine in Space",
		instagramProfileURL: "https://www.instagram.com/submarine_in_space",
		imageURL: require("../../../../public/assets/new-homepage/submarine_in_space.png"),
		description: "The Critically Acclaimed IInstrumental Jazz-Rock Band",
		bgURL_d: require("../../../../public/assets/new-homepage/cover_submarine.png"),
		bgURL_m: require("../../../../public/assets/new-homepage/cover_m.png"),
	},
	{
		name: "Sommaiya",
		instagramProfileURL: "https://www.instagram.com/sommaiya_angrish",
		imageURL: require("../../../../public/assets/new-homepage/sommaiya.png"),
		description: "A Genreless Musician and Filmmaker leaving his mark from New Delhi to New York",
		bgURL_d: require("../../../../public/assets/new-homepage/cover_sommaiya.png"),
		bgURL_m: require("../../../../public/assets/new-homepage/cover_m.png"),
	},
	{
		name: "Harry Arora",
		instagramProfileURL: "https://www.instagram.com/harrythisside",
		imageURL: require("../../../../public/assets/new-homepage/harry.png"),
		description: "The singer touching all the right chords",
		bgURL_d: require("../../../../public/assets/new-homepage/cover_harry.png"),
		bgURL_m: require("../../../../public/assets/new-homepage/cover_m.png"),
	},
	{
		name: "Xubaan",
		instagramProfileURL: "https://www.instagram.com/xubaanindia",
		imageURL: require("../../../../public/assets/new-homepage/jatayu.png"),
		description: "The band that is taking the world by storm",
		bgURL_d: require("../../../../public/assets/new-homepage/cover_xubaan.png"),
		bgURL_m: require("../../../../public/assets/new-homepage/cover_m.png"),
	},
];
