const trackOrigin  = [
    "Original",
    "Cover",
    "Remix",
    "Live",
    "Remastered",
    "Radio Edit",
    "Instrumental",
    "Bonus Cut",
    "Acapella",
    "Acoustic",
    "Extended version",
    "Deluxe",
    "Original Motion Picture Soundtrack",
    "Production Music",
    "Single Edit",
    "Mashup",
    "Bootleg remix",
    "Explicit version",
    "Clean version ",
    "Lo-fi version",
    "Reverb",
    "Duet",
    "Parody",
];
const genre  = [
    "Acoustic",
    "Alternative",
    "Anime",
    "Big Band",
    "Blues",
    "Children’s Music",
    "Classical",
    "Comedy",
    "Commercial",
    "Contemporary",
    "Country",
    "Dance",
    "Dance-pop",
    "Disney",
    "Easy Listening",
    "Electronic",
    "Enka",
    "French Pop",
    "Folk",
    "German Folk",
    "German Pop",
    "Fitness & Workout",
    "Hip-Hop",
    "Holiday",
    "Indie Folk",
    "Indie Pop",
    "Industrial",
    "Inspirational",
    "Instrumental",
    "J-Pop",
    "Jazz",
    "Jingles",
    "K-Pop",
    "Karaoke",
    "Kayokyoku",
    "Latin",
    "Lo-fi",
    "Lullabies",
    "Metal",
    "Musical",
    "New Age",
    "Opera",
    "Pop",
    "Post-Disco",
    "Progressive",
    "Punk",
    "R&B",
    "Rap",
    "Reggae",
    "Rock",
    "Soundtrack",
    "Spoken Word",
    "Stories",
    "Tex-Mex/Tejano",
    "Vocal",
];
const parentalAdvisory  = [
    "Explicit",
    "Clean (There is another version of this track that is explicit, but this is the clean version)",
    "Not Explicit",
];
const duration  = ["< 100s","100-150s", "150-200s", "200-250s","250-300s","> 300s"];
const numberOfCollaborators = [1,2,3,4,5];
const nftStatus = ["On Sale", "Not on Sale"];
const numberOfCopies = ["1 (Single Drop)", "2-10", "10-20","20-30","30-40","40-50","50-60","60-70","70-80","80-90","90-100","> 100"];
const resaleRoyalty = ["5%","6%-10%", "10%-20%","20%-30%","30%-40%","40%-50%","50%-60%","60%-70%","70%-80%","80%-90%","90%-100%"];
const countryOfOrigin = ["India", "Rest of the world"];
export {genre , parentalAdvisory , trackOrigin, duration, numberOfCollaborators, numberOfCopies, nftStatus, resaleRoyalty, countryOfOrigin };