const trackOrigin  = [
    "Original",
    "Cover",
    "Remix",
    "Live",
    "Remastered",
    "Radio Edit",
    "Instrumental",
    "Bonus Cut",
    "Acapella",
    "Acoustic",
    "Extended version",
    "Deluxe",
    "Original Motion Picture Soundtrack",
    "Production Music",
    "Single Edit",
    "Mashup",
    "Bootleg remix",
    "Explicit version",
    "Clean version ",
    "Lo-fi version",
    "Reverb",
    "Duet",
    "Parody",
];
const genre  = [
    "Acoustic",
    "Alternative",
    "Anime",
    "Big Band",
    "Blues",
    "Children’s Music",
    "Classical",
    "Comedy",
    "Commercial",
    "Contemporary",
    "Country",
    "Dance",
    "Dance-pop",
    "Disney",
    "Easy Listening",
    "Electronic",
    "Enka",
    "French Pop",
    "Folk",
    "German Folk",
    "German Pop",
    "Fitness & Workout",
    "Hip-Hop",
    "Holiday",
    "Indie Folk",
    "Indie Pop",
    "Industrial",
    "Inspirational",
    "Instrumental",
    "J-Pop",
    "Jazz",
    "Jingles",
    "K-Pop",
    "Karaoke",
    "Kayokyoku",
    "Latin",
    "Lo-fi",
    "Lullabies",
    "Metal",
    "Musical",
    "New Age",
    "Opera",
    "Pop",
    "Post-Disco",
    "Progressive",
    "Punk",
    "R&B",
    "Rap",
    "Reggae",
    "Rock",
    "Soundtrack",
    "Spoken Word",
    "Stories",
    "Tex-Mex/Tejano",
    "Vocal",
];
const parentalAdvisory  = [
    "Explicit",
    "Clean (There is another version of this track that is explicit, but this is the clean version)",
    "Not Explicit",
];
const duration  = ["< 100s","100-150s", "150-200s", "200-250s","250-300s","> 300s"];
const numberOfCollaborators = [1,2,3,4,5];
const nftStatus = ["On Sale", "Not on Sale"];
const numberOfCopies = ["1 (Single Drop)", "2-10", "10-20","20-30","30-40","40-50","50-60","60-70","70-80","80-90","90-100","> 100"];
const resaleRoyalty = ["5%","6%-10%", "10%-20%","20%-30%","30%-40%","40%-50%","50%-60%","60%-70%","70%-80%","80%-90%","90%-100%"];
const countryOfOrigin = ["India", "Rest of the world"];
const tagsAvailable = [
    { value: "Aggressive", label: "Aggressive" },
    { value: "Alternative", label: "Alternative" },
    { value: "Angry", label: "Angry" },
    { value: "Beautiful", label: "Beautiful" },
    { value: "Calm", label: "Calm" },
    { value: "Cheerful", label: "Cheerful" },
    { value: "Chill", label: "Chill" },
    { value: "Cool", label: "Cool" },
    { value: "Country", label: "Country" },
    { value: "Dance", label: "Dance" },
    { value: "Delicate", label: "Delicate" },
    { value: "Depressing", label: "Depressing" },
    { value: "Dreamy", label: "Dreamy" },
    { value: "Electronic", label: "Electronic" },
    { value: "Exciting", label: "Exciting" },
    { value: "Fierce", label: "Fierce" },
    { value: "Folk", label: "Folk" },
    { value: "Fun", label: "Fun" },
    { value: "Gloomy", label: "Gloomy" },
    { value: "Happy", label: "Happy" },
    { value: "Hostile", label: "Hostile" },
    { value: "Humorous", label: "Humorous" },
    { value: "Indie", label: "Indie" },
    { value: "Jazz", label: "Jazz" },
    { value: "Joyful", label: "Joyful" },
    { value: "Love", label: "Love" },
    { value: "Lyrical", label: "Lyrical" },
    { value: "Merry", label: "Merry" },
    { value: "Metal", label: "Metal" },
    { value: "Miserable", label: "Miserable" },
    { value: "Oldies", label: "Oldies" },
    { value: "Patriotic", label: "Patriotic" },
    { value: "Peaceful", label: "Peaceful" },
    { value: "Pop", label: "Pop" },
    { value: "Quiet", label: "Quiet" },
    { value: "Rebellious", label: "Rebellious" },
    { value: "Relaxed", label: "Relaxed" },
    { value: "Rock", label: "Rock" },
    { value: "Sad", label: "Sad" },
    { value: "Sadness", label: "Sadness" },
    { value: "Satisfying", label: "Satisfying" },
    { value: "Silly", label: "Silly" },
    { value: "Sleepy", label: "Sleepy" },
    { value: "Soft", label: "Soft" },
    { value: "Somber", label: "Somber" },
    { value: "Soothing", label: "Soothing" },
    { value: "Sorrow", label: "Sorrow" },
    { value: "Soul", label: "Soul" },
    { value: "Tense", label: "Tense" },
    { value: "Tragic", label: "Tragic" },
    { value: "80s", label: "80s" },
    { value: "90s", label: "90s" },
];

export {genre , parentalAdvisory , trackOrigin, duration, numberOfCollaborators, numberOfCopies, nftStatus, resaleRoyalty, countryOfOrigin, tagsAvailable };