import Head from "next/head";
import styles from "../styles/Home.module.css";

function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Musixverse</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Musixverse</h1>

                <p className={styles.description}>Supporting creators through Crypto</p>
            </main>
        </div>
    );
}

export default Home;
