import MusixverseFacet from "./utils/smart-contract/contracts/Musixverse/facets/MusixverseFacet.sol/MusixverseFacet.json";

/**************************************************************************/
/**********************    SEO Meta Descriptions   ************************/
/**************************************************************************/
export const title_main_page = "Musixverse | The Ultimate Music NFT Marketplace";
export const meta_description =
	"Musixverse is a Music NFT marketplace that will bring Artists and Fans together like never before and unlock novel models of communications and commerce.";
export const meta_description2 = "Powering music ownership and provenance across the web and beyond";
export const meta_description3 = "The NFT Marketplace for Musicians and Fans";

/**************************************************************************/
/***********************    BLOCKCHAIN CONSTANTS  *************************/
/**************************************************************************/
export const MUSIXVERSE_FACET_CONTRACT_ABI = MusixverseFacet.abi;
export const MXV_DIAMOND_ADDRESS = "0x78e1a1a665D1065cdf283a1AcD39A76BE3B6c093"; // Diamond Address
export const MUSIXVERSE_FACET_ADDRESS = "0x789aabC3f3691B1b4691CC8a5093E767c2c3ca8E";
export const MUSIXVERSE_GETTERS_FACET_ADDRESS = "0xe5a0D685d6b34CfD18C2648098a09912F4e3e88f";
export const MUSIXVERSE_SETTERS_FACET_ADDRESS = "0x08De2F648b54be5033f9134a5819Fa9fAC8b4129";
export const BLOCKCHAIN_NETWORK = "mumbai";
export const BLOCK_EXPLORER_URL = "https://mumbai.polygonscan.com";
export const BLOCKCHAIN_NETWORK_ID = 80001;
export const RPC_URL = "https://polygon-mumbai.g.alchemy.com/v2/8qorAGwStqgObuxITbYVAD3T2BI1jC36";

/**************************************************************************/
/************************    TRACK ATTRIBUTES    **************************/
/**************************************************************************/
export const trackOriginArray = [
	"Original",
	"Cover",
	"Remix",
	"Live",
	"Remastered",
	"Radio Edit",
	"Instrumental",
	"Bonus Cut",
	"Acapella",
	"Acoustic",
	"Extended version",
	"Deluxe",
	"Original Motion Picture Soundtrack",
	"Production Music",
	"Single Edit",
	"Mashup",
	"Bootleg remix",
	"Explicit version",
	"Clean version ",
	"Lo-fi version",
	"Reverb",
	"Duet",
	"Parody",
];
export const genreArray = [
	"Acoustic",
	"Alternative",
	"Anime",
	"Big Band",
	"Blues",
	"Children’s Music",
	"Classical",
	"Comedy",
	"Commercial",
	"Contemporary",
	"Country",
	"Dance",
	"Dance-pop",
	"Disney",
	"Easy Listening",
	"Electronic",
	"Enka",
	"French Pop",
	"Folk",
	"German Folk",
	"German Pop",
	"Fitness & Workout",
	"Hip-Hop",
	"Holiday",
	"Indie Folk",
	"Indie Pop",
	"Industrial",
	"Inspirational",
	"Instrumental",
	"J-Pop",
	"Jazz",
	"Jingles",
	"K-Pop",
	"Karaoke",
	"Kayokyoku",
	"Latin",
	"Lo-fi",
	"Lullabies",
	"Metal",
	"Musical",
	"New Age",
	"Opera",
	"Pop",
	"Post-Disco",
	"Progressive",
	"Punk",
	"R&B",
	"Rap",
	"Reggae",
	"Rock",
	"Soundtrack",
	"Spoken Word",
	"Stories",
	"Tex-Mex/Tejano",
	"Vocal",
];
export const parentalAdvisoryArray = [
	"Explicit",
	"Clean (There is another version of this track that is explicit, but this is the clean version)",
	"Not Explicit",
];
export const languageArray = [
	"Hindi",
	"English",
	"Arabic",
	"Armenian",
	"Assamese",
	"Awadhi",
	"Bengali",
	"Bhojpuri",
	"Chinese",
	"Czech",
	"Danish",
	"Dutch",
	"English",
	"Filipino",
	"Finnish",
	"French",
	"German",
	"Greek",
	"Gujarati",
	"Haryanvi",
	"Hebrew",
	"Hindi",
	"Hungarian",
	"Icelandic",
	"Indonesian",
	"Irish",
	"Italian",
	"Japanese",
	"Kannada",
	"Kashmiri",
	"Konkani",
	"Korean",
	"Malayalam",
	"Maltese",
	"Mandarin",
	"Marathi",
	"Nepali",
	"Odia",
	"Pahari",
	"Persian",
	"Polish",
	"Portuguese",
	"Punjabi",
	"Rajasthani",
	"Romanian",
	"Russian",
	"Serbian",
	"Spanish",
	"Swedish",
	"Tamil",
	"Telugu",
	"Thai",
	"Turkish",
	"Ukrainian",
	"Urdu",
];
export const tagsAvailable = [
	{ value: "Aggressive", label: "Aggressive" },
	{ value: "Alternative", label: "Alternative" },
	{ value: "Angry", label: "Angry" },
	{ value: "Beautiful", label: "Beautiful" },
	{ value: "Calm", label: "Calm" },
	{ value: "Cheerful", label: "Cheerful" },
	{ value: "Chill", label: "Chill" },
	{ value: "Cool", label: "Cool" },
	{ value: "Country", label: "Country" },
	{ value: "Dance", label: "Dance" },
	{ value: "Delicate", label: "Delicate" },
	{ value: "Depressing", label: "Depressing" },
	{ value: "Dreamy", label: "Dreamy" },
	{ value: "Electronic", label: "Electronic" },
	{ value: "Exciting", label: "Exciting" },
	{ value: "Fierce", label: "Fierce" },
	{ value: "Folk", label: "Folk" },
	{ value: "Fun", label: "Fun" },
	{ value: "Gloomy", label: "Gloomy" },
	{ value: "Happy", label: "Happy" },
	{ value: "Hostile", label: "Hostile" },
	{ value: "Humorous", label: "Humorous" },
	{ value: "Indie", label: "Indie" },
	{ value: "Jazz", label: "Jazz" },
	{ value: "Joyful", label: "Joyful" },
	{ value: "Love", label: "Love" },
	{ value: "Lyrical", label: "Lyrical" },
	{ value: "Merry", label: "Merry" },
	{ value: "Metal", label: "Metal" },
	{ value: "Miserable", label: "Miserable" },
	{ value: "Oldies", label: "Oldies" },
	{ value: "Patriotic", label: "Patriotic" },
	{ value: "Peaceful", label: "Peaceful" },
	{ value: "Pop", label: "Pop" },
	{ value: "Quiet", label: "Quiet" },
	{ value: "Rebellious", label: "Rebellious" },
	{ value: "Relaxed", label: "Relaxed" },
	{ value: "Rock", label: "Rock" },
	{ value: "Sad", label: "Sad" },
	{ value: "Sadness", label: "Sadness" },
	{ value: "Satisfying", label: "Satisfying" },
	{ value: "Silly", label: "Silly" },
	{ value: "Sleepy", label: "Sleepy" },
	{ value: "Soft", label: "Soft" },
	{ value: "Somber", label: "Somber" },
	{ value: "Soothing", label: "Soothing" },
	{ value: "Sorrow", label: "Sorrow" },
	{ value: "Soul", label: "Soul" },
	{ value: "Tense", label: "Tense" },
	{ value: "Tragic", label: "Tragic" },
	{ value: "80s", label: "80s" },
	{ value: "90s", label: "90s" },
];
export const countryOfOriginArray = [
	"India",
	"Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bhutan",
	"Bolivia",
	"Bosnia and Herzegovina",
	"Botswana",
	"Brazil",
	"Brunei",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Central African Republic (CAR)",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Comoros",
	"Congo, Democratic Republic of the",
	"Congo, Republic of the",
	"Costa Rica",
	"Cote d'Ivoire",
	"Croatia",
	"Cuba",
	"Cyprus",
	"Czechia",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Fiji",
	"Finland",
	"France",
	"Gabon",
	"Gambia",
	"Georgia",
	"Germany",
	"Ghana",
	"Greece",
	"Grenada",
	"Guatemala",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Honduras",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Kosovo",
	"Kuwait",
	"Kyrgyzstan",
	"Laos",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Mauritania",
	"Mauritius",
	"Mexico",
	"Micronesia",
	"Moldova",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"North Korea",
	"North Macedonia",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestine",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Qatar",
	"Romania",
	"Russia",
	"Rwanda",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Korea",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Suriname",
	"Sweden",
	"Switzerland",
	"Syria",
	"Taiwan",
	"Tajikistan",
	"Tanzania",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates (UAE)",
	"United Kingdom (UK)",
	"United States of America (USA)",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Vatican City (Holy See)",
	"Venezuela",
	"Vietnam",
	"Yemen",
	"Zambia",
	"Zimbabwe",
];

/**************************************************************************/
/***********************    MARKETPLACE FILTERS    ************************/
/**************************************************************************/
export const duration = ["<100s", "100-150s", "151-200s", "201-250s", "251-300s", "301-350s", "351-400s", ">400s"];
export const numberOfCollaborators = [1, 2, 3, 4, 5];
export const nftStatus = ["On Sale", "Not on Sale", "Coming Soon"];
export const numberOfCopies = [
	"1 (Single Drop)",
	"2",
	"3",
	"4",
	"5",
	"6-10",
	"11-20",
	"21-30",
	"31-40",
	"41-50",
	"51-60",
	"61-70",
	"71-80",
	"81-90",
	"91-100",
	">100",
];
export const resaleRoyalty = [
	"1%",
	"2%",
	"3%",
	"4%",
	"5%",
	"6%-10%",
	"11%-20%",
	"21%-30%",
	"31%-40%",
	"41%-50%",
	"51%-60%",
	"61%-70%",
	"71%-80%",
	"81%-90%",
	"91%-100%",
];

export const locationArray = [];
